package calculator;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

import com.qa.calculator.Calculator;

public class CalculatorTest {
	@Test
	public void multiplyTestwithmultiply1() {
		Calculator calculator = new Calculator();
		assertEquals(4, calculator.multiply(2, 2));
	}
	
	@Test
	public void multiplyTestwithmultiply2() {
		Calculator calculator = new Calculator();
		assertEquals(6, calculator.multiply(3, 2));}
	
	@Test(expected = ArithmeticException.class)
	public void multiplyTestwithdivide1() {
		Calculator calculator = new Calculator();
		assertEquals(2, calculator.divide(5, 0));}
	
	@Test
	public void multiplyTestwithdivide2() {
		Calculator calculator = new Calculator();
		assertEquals(5, calculator.divide(10, 2));}
	
	@Test
	public void multiplyTestwithadd1() {
		Calculator calculator = new Calculator();
		assertEquals(5, calculator.add(3, 2));}
	
	@Test
	public void multiplyTestwithadd2() {
		Calculator calculator = new Calculator();
		assertEquals(5, calculator.add(3, 2));}
	
	@Test
	public void multiplyTestwithsubtract1() {
		Calculator calculator = new Calculator();
		assertEquals(1, calculator.subtract(3, 2));}
	
	@Test
	public void multiplyTestwithsubtract2() {
		Calculator calculator = new Calculator();
		assertEquals(1, calculator.subtract(3, 2));}
	
}
